In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-01-26/plastics.csv')

In [4]:
data.head(20)

,country,year,parent_company,empty,hdpe,ldpe,o,pet,pp,ps,pvc,grand_total,num_events,volunteers
0,Argentina,2019,Grand Total,0.0,215.0,55.0,607.0,1376.0,281.0,116.0,18.0,2668.0,4,243.0
1,Argentina,2019,Unbranded,0.0,155.0,50.0,532.0,848.0,122.0,114.0,17.0,1838.0,4,243.0
2,Argentina,2019,The Coca-Cola Company,0.0,0.0,0.0,0.0,222.0,35.0,0.0,0.0,257.0,4,243.0
3,Argentina,2019,Secco,0.0,0.0,0.0,0.0,39.0,4.0,0.0,0.0,43.0,4,243.0
4,Argentina,2019,Doble Cola,0.0,0.0,0.0,0.0,38.0,0.0,0.0,0.0,38.0,4,243.0
5,Argentina,2019,Pritty,0.0,0.0,0.0,0.0,22.0,7.0,0.0,0.0,29.0,4,243.0
6,Argentina,2019,PepsiCo,0.0,0.0,0.0,0.0,21.0,6.0,0.0,0.0,27.0,4,243.0
7,Argentina,2019,Casoni,0.0,0.0,0.0,0.0,26.0,0.0,0.0,0.0,26.0,4,243.0
8,Argentina,2019,Villa Del Sur - Levite,0.0,0.0,0.0,0.0,19.0,1.0,0.0,0.0,20.0,4,243.0
9,Argentina,2019,Manaos,0.0,0.0,0.0,0.0,14.0,4.0,0.0,0.0,18.0,4,243.0
10,Argentina,2019,La Bichy Ahora,0.0,0.0,0.0,0.0,14.0,3.0,0.0,0.0,17.0,4,243.0
11,Argentina,2019,Villavicencio,0.0,0.0,0.0,0.0,14.0,1.0,0.0,0.0,15.0,4,243.0
12,Argentina,2019,Eco De Los Andes,0.0,0.0,0.0,0.0,14.0,0.0,0.0,0.0,14.0,4,243.0
13,Argentina,2019,Cavatini,0.0,0.0,0.0,13.0,0.0,0.0,0.0,0.0,13.0,4,243.0
14,Argentina,2019,Villa Del Sur,0.0,0.0,0.0,0.0,8.0,3.0,0.0,0.0,11.0,4,243.0
15,Argentina,2019,Cepita,0.0,0.0,0.0,0.0,9.0,0.0,0.0,0.0,9.0,4,243.0
16,Argentina,2019,Livra,0.0,0.0,0.0,0.0,5.0,4.0,0.0,0.0,9.0,4,243.0
17,Argentina,2019,Nestlé,0.0,1.0,0.0,0.0,6.0,2.0,0.0,0.0,9.0,4,243.0
18,Argentina,2019,Vino Toro,0.0,0.0,0.0,8.0,0.0,0.0,0.0,0.0,8.0,4,243.0
19,Argentina,2019,Frutafiel,0.0,0.0,0.0,0.0,6.0,1.0,0.0,0.0,7.0,4,243.0

In [26]:
data2 = data[['year','parent_company','empty','hdpe','ldpe','o','pet','pp','ps','pvc','grand_total']].groupby(by=['year','parent_company'], as_index=False).sum()

In [32]:
data2.sort_values(by=['grand_total','year'], ascending=False)

,year,parent_company,empty,hdpe,ldpe,o,pet,pp,ps,pvc,grand_total
2618,2019,Grand Total,0.0,9320.0,39589.0,259069.0,96898.0,17988.0,5890.0,477.0,429231.0
6781,2019,Unbranded,0.0,4025.0,16208.0,198818.0,17111.0,10054.0,4354.0,186.0,250756.0
10923,2020,Unbranded,3031.0,7711.0,10594.0,65839.0,11529.0,8220.0,5346.0,1049.0,113319.0
3676,2019,La Doo,0.0,0.0,0.0,0.0,15221.0,0.0,0.0,0.0,15221.0
10808,2020,The Coca-Cola Company,23.0,734.0,364.0,305.0,11498.0,854.0,8.0,49.0,13835.0
...,...,...,...,...,...,...,...,...,...,...,...
7886,2019,Ã–ttingen,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7887,2019,Ã‡ENESUYU,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7888,2019,Ã‡obanpÄ±nar,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7889,2019,Ã‡okkolata,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7890,2019,Ä°Ã§im,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [29]:
data2[data2['parent_company']=='The Coca-Cola Company']
#data2['parent_company']

,year,parent_company,empty,hdpe,ldpe,o,pet,pp,ps,pvc,grand_total
6509,2019,The Coca-Cola Company,0.0,876.0,59.0,964.0,9247.0,454.0,44.0,51.0,11695.0
10808,2020,The Coca-Cola Company,23.0,734.0,364.0,305.0,11498.0,854.0,8.0,49.0,13835.0

In [17]:
data['country'].unique()

array(['Argentina', 'Australia', 'Bangladesh', 'Benin', 'Bhutan',
       'Brazil', 'Bulgaria', 'Burkina Faso', 'Cameroon', 'Canada',
       'China', 'Colombia', 'Cote D_ivoire', 'Cyprus', 'ECUADOR', 'EMPTY',
       'France', 'Germany', 'Ghana', 'Hong Kong', 'India', 'Indonesia',
       'Ireland', 'Italy', 'Japan', 'Kenya', 'Latvia', 'Luxembourg',
       'Malaysia', 'Maldives', 'Mexico', 'Montenegro', 'NIGERIA',
       'Netherlands', 'Philippines', 'Portugal', 'Rwanda', 'Slovenia',
       'South Africa', 'Spain', 'Sri Lanka', 'Switzerland',
       'Taiwan_ Republic of China (ROC)', 'Tanzania', 'Thailand',
       'Tunisia', 'Turkey', 'Ukraine', 'United Arab Emirates',
       'United Kingdom', 'United States of America', 'Vietnam', 'Armenia',
       'Chile', 'Denmark', 'Ecuador', 'El Salvador', 'Greece', 'Honduras',
       'Korea', 'Kuwait', 'Lithuania', 'Nigeria', 'Peru', 'Romania',
       'Serbia', 'Singapore', 'Togo',
       'United Kingdom of Great Britain & Northern Ireland'], dtype=object)